### ISSUE TITLE
Redirect user to grant approval after login

### ISSUE THREAD

**Issue by raducristianpopa** [interledger/testnet#738] opened 2023-09-13 13:55 UTC
Redirecting the user for a grant interaction, will cause a grant "miss" if the user is not authenticated. We need to ensure that the user gets redirected to that specific grant request for interaction after logging in into the wallet.

**Comment by Tymmmy** [comment] 2023-09-20 06:49
Duplicate of #748

**Closed** 2023-09-20 06:48 UTC
Labels: package: commerce/frontend
